# Generated by Django 4.2.7 on 2024-01-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tech',
            field=models.CharField(default='Juan Perez', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tech_CI',
            field=models.PositiveIntegerField(default='92121354653'),
        ),
    ]
